import { standardPreset } from "@/defaults/variants/presets";
import { createValues } from "@/helpers/create-values";
import type { Utilities } from "@/interfaces";

export const transform: Utilities = {
	rotate: {
		prefix: "ro",
		properties: ["rotate"],
		slug: "rotate",
		values: createValues({
			base: 5,
			unit: "deg",
			min: 0,
			max: 360,
		}),
		variants: standardPreset,
	},

	scale: {
		prefix: "t-s",
		properties: ["transform"],
		slug: "scale",
		values: {
			"0": "scale(0%)",
			"10": "scale(10%)",
			"20": "scale(20%)",
			"30": "scale(30%)",
			"40": "scale(40%)",
			"50": "scale(50%)",
			"60": "scale(60%)",
			"70": "scale(70%)",
			"80": "scale(80%)",
			"90": "scale(90%)",
			"100": "scale(100%)",
		},
		variants: standardPreset,
	},

	"scale-x": {
		prefix: "t-sx",
		properties: ["transform"],
		slug: "scale-x",
		values: {
			"0": "scaleX(0%)",
			"10": "scaleX(10%)",
			"20": "scaleX(20%)",
			"30": "scaleX(30%)",
			"40": "scaleX(40%)",
			"50": "scaleX(50%)",
			"60": "scaleX(60%)",
			"70": "scaleX(70%)",
			"80": "scaleX(80%)",
			"90": "scaleX(90%)",
			"100": "scaleX(100%)",
		},
		variants: standardPreset,
	},

	"scale-y": {
		prefix: "t-sy",
		properties: ["transform"],
		slug: "scale-y",
		values: {
			"0": "scaleY(0%)",
			"10": "scaleY(10%)",
			"20": "scaleY(20%)",
			"30": "scaleY(30%)",
			"40": "scaleY(40%)",
			"50": "scaleY(50%)",
			"60": "scaleY(60%)",
			"70": "scaleY(70%)",
			"80": "scaleY(80%)",
			"90": "scaleY(90%)",
			"100": "scaleY(100%)",
		},
		variants: standardPreset,
	},

	skew: {
		prefix: "t-sk",
		properties: ["transform"],
		slug: "skew",
		values: {
			"1": "skew(1deg)",
			"2": "skew(2deg)",
			"3": "skew(3deg)",
			"6": "skew(6deg)",
			"12": "skew(12deg)",
		},
		variants: standardPreset,
	},

	"skew-x": {
		prefix: "t-skx",
		properties: ["transform"],
		slug: "skew-x",
		values: {
			"1": "skewX(1deg)",
			"2": "skewX(2deg)",
			"3": "skewX(3deg)",
			"6": "skewX(6deg)",
			"12": "skewX(12deg)",
		},
		variants: standardPreset,
	},

	"skew-y": {
		prefix: "t-sky",
		properties: ["transform"],
		slug: "skew-y",
		values: {
			"1": "skewY(1deg)",
			"2": "skewY(2deg)",
			"3": "skewY(3deg)",
			"6": "skewY(6deg)",
			"12": "skewY(12deg)",
		},
		variants: standardPreset,
	},

	"transform-origin": {
		prefix: "t-o",
		properties: ["transform-origin"],
		slug: "transform-origin",
		values: {
			b: "bottom",
			bl: "bottom left",
			br: "bottom right",
			c: "center",
			l: "left",
			r: "right",
			t: "top",
			tl: "top left",
			tr: "top right",
		},
		variants: standardPreset,
	},

	"translate-x": {
		prefix: "t-tx",
		properties: ["transform"],
		slug: "translate-x",
		values: {
			"0": "translateX(0)",
			"1": "translateX(0.25rem)",
			"2": "translateX(0.5rem)",
			"3": "translateX(0.75rem)",
			"4": "translateX(1rem)",
			"5": "translateX(1.25rem)",
			"6": "translateX(1.5rem)",
			"7": "translateX(1.75rem)",
			"8": "translateX(2rem)",
			"9": "translateX(2.25rem)",
			"10": "translateX(2.5rem)",
			"11": "translateX(2.75rem)",
			"12": "translateX(3rem)",
			"13": "translateX(3.25rem)",
			"14": "translateX(3.5rem)",
			"15": "translateX(3.75rem)",
			"16": "translateX(4rem)",
			"17": "translateX(4.25rem)",
			"18": "translateX(4.5rem)",
			"19": "translateX(4.75rem)",
			"20": "translateX(5rem)",
			"21": "translateX(5.25rem)",
			"22": "translateX(5.5rem)",
			"23": "translateX(5.75rem)",
			"24": "translateX(6rem)",
			"25": "translateX(6.25rem)",
			"26": "translateX(6.5rem)",
			"27": "translateX(6.75rem)",
			"28": "translateX(7rem)",
			"29": "translateX(7.25rem)",
			"30": "translateX(7.5rem)",
			"31": "translateX(7.75rem)",
			"32": "translateX(8rem)",
			"64": "translateX(16rem)",
			"96": "translateX(24rem)",
			full: "translateX(100%)",
			half: "translateX(50%)",
		},
		variants: standardPreset,
	},

	"translate-y": {
		prefix: "t-ty",
		properties: ["transform"],
		slug: "translate-y",
		values: {
			"0": "translateY(0)",
			"1": "translateY(0.25rem)",
			"2": "translateY(0.5rem)",
			"3": "translateY(0.75rem)",
			"4": "translateY(1rem)",
			"5": "translateY(1.25rem)",
			"6": "translateY(1.5rem)",
			"7": "translateY(1.75rem)",
			"8": "translateY(2rem)",
			"9": "translateY(2.25rem)",
			"10": "translateY(2.5rem)",
			"11": "translateY(2.75rem)",
			"12": "translateY(3rem)",
			"13": "translateY(3.25rem)",
			"14": "translateY(3.5rem)",
			"15": "translateY(3.75rem)",
			"16": "translateY(4rem)",
			"17": "translateY(4.25rem)",
			"18": "translateY(4.5rem)",
			"19": "translateY(4.75rem)",
			"20": "translateY(5rem)",
			"21": "translateY(5.25rem)",
			"22": "translateY(5.5rem)",
			"23": "translateY(5.75rem)",
			"24": "translateY(6rem)",
			"25": "translateY(6.25rem)",
			"26": "translateY(6.5rem)",
			"27": "translateY(6.75rem)",
			"28": "translateY(7rem)",
			"29": "translateY(7.25rem)",
			"30": "translateY(7.5rem)",
			"31": "translateY(7.75rem)",
			"32": "translateY(8rem)",
			"64": "translateY(16rem)",
			"96": "translateY(24rem)",
			full: "translateY(100%)",
			half: "translateY(50%)",
		},
		variants: standardPreset,
	},
};
