export const mediaQueries = [
	{ prefix: "pc", value: "@media (pointer: coarse)" },
	{ prefix: "prm", value: "@media (prefers-reduced-motion: reduce)" },
	{ prefix: "xs", value: "@media (min-width: 32rem)" },
	{ prefix: "sm", value: "@media (min-width: 40rem)" },
	{ prefix: "md", value: "@media (min-width: 48rem)" },
	{ prefix: "lg", value: "@media (min-width: 64rem)" },
	{ prefix: "xl", value: "@media (min-width: 80rem)" },
	{ prefix: "xxl", value: "@media (min-width: 96rem)" },
	{ prefix: "c:xs", value: "@container (min-width: 32rem)" },
	{ prefix: "c:sm", value: "@container (min-width: 40rem)" },
	{ prefix: "c:md", value: "@container (min-width: 48rem)" },
	{ prefix: "c:lg", value: "@container (min-width: 64rem)" },
	{ prefix: "c:xl", value: "@container (min-width: 80rem)" },
	{ prefix: "c:xxl", value: "@container (min-width: 96rem)" },
] as const;
